sudo: required
language: generic 
services:
  - docker


before_install: 
  - docker build -t grassper/react-test -f ./client/Dockerfile.local ./client

script: 
  - docker run -e CI=true grassper/react-test npm test

after_success: 
  - docker build -t grassper/multi-client ./client
  - docker build -t grassper/multi-nginx ./nginx
  - docker build -t grassper/multi-server ./server
  - docker build -t grassper/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  # Take those images and push them to docker hub
  - docker push grassper/multi-client
  - docker push grassper/multi-nginx
  - docker push grassper/multi-server
  - docker push grassper/multi-worker