  services:
    nginx:
      image: "grassper/multi-nginx"
      restart: always
      hostname: nginx
      mem_limit: 128m
      ports:
        - "80:80"
      depends_on:
        - client
        - server
    client:
      image: "grassper/multi-client"
      hostname: client
      mem_limit: 128m
    server:
      image: "grassper/multi-server"
      hostname: server
      mem_limit: 128m
      environment:
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - PGUSER=${PGUSER}
        - PGHOST=${PGHOST}
        - PGDATABASE=${PGDATABASE}
        - PGPASSWORD=${PGPASSWORD}
        - PGPORT=${PGPORT}
    worker:
      image: "grassper/multi-worker"
      hostname: worker
      mem_limit: 128m
      environment:
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
