version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
  redis:
    image: "redis:latest"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - "3080:80"
    depends_on:
      - client
      - server
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.local
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
