name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t grassper/react-test -f ./client/Dockerfile.local ./client
      - run: docker run -e CI=true grassper/react-test npm test

      - run: docker build -t grassper/multi-client ./client
      - run: docker build -t grassper/multi-nginx ./nginx
      - run: docker build -t grassper/multi-server ./server
      - run: docker build -t grassper/multi-worker ./worker

      - run: docker push grassper/multi-client
      - run: docker push grassper/multi-nginx
      - run: docker push grassper/multi-server
      - run: docker push grassper/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container
          environment_name: Multi-container-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-637423255917
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
